/*
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.GameBoxscoreTeamPlayersPerson;
import org.openapitools.client.model.GameBoxscoreTeamPlayersPosition;
import org.openapitools.client.model.GameBoxscoreTeamPlayersStats;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GameBoxscoreTeamPlayers
 */
public class GameBoxscoreTeamPlayersTest {
    private final GameBoxscoreTeamPlayers model = new GameBoxscoreTeamPlayers();

    /**
     * Model tests for GameBoxscoreTeamPlayers
     */
    @Test
    public void testGameBoxscoreTeamPlayers() {
        // TODO: test GameBoxscoreTeamPlayers
    }

    /**
     * Test the property 'person'
     */
    @Test
    public void personTest() {
        // TODO: test person
    }

    /**
     * Test the property 'jerseyNumber'
     */
    @Test
    public void jerseyNumberTest() {
        // TODO: test jerseyNumber
    }

    /**
     * Test the property 'position'
     */
    @Test
    public void positionTest() {
        // TODO: test position
    }

    /**
     * Test the property 'stats'
     */
    @Test
    public void statsTest() {
        // TODO: test stats
    }

}
