/*
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.net.URI;
import org.openapitools.client.model.GameGameData;
import org.openapitools.client.model.GameLiveData;
import org.openapitools.client.model.GameMetaData;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Game
 */
public class GameTest {
    private final Game model = new Game();

    /**
     * Model tests for Game
     */
    @Test
    public void testGame() {
        // TODO: test Game
    }

    /**
     * Test the property 'copyright'
     */
    @Test
    public void copyrightTest() {
        // TODO: test copyright
    }

    /**
     * Test the property 'gamePk'
     */
    @Test
    public void gamePkTest() {
        // TODO: test gamePk
    }

    /**
     * Test the property 'link'
     */
    @Test
    public void linkTest() {
        // TODO: test link
    }

    /**
     * Test the property 'metaData'
     */
    @Test
    public void metaDataTest() {
        // TODO: test metaData
    }

    /**
     * Test the property 'gameData'
     */
    @Test
    public void gameDataTest() {
        // TODO: test gameData
    }

    /**
     * Test the property 'liveData'
     */
    @Test
    public void liveDataTest() {
        // TODO: test liveData
    }

}
