/*
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.GameGameDataStatus;
import org.openapitools.client.model.GameGameDataVenue;
import org.openapitools.client.model.GameLinescore;
import org.openapitools.client.model.ScheduleGameContent;
import org.openapitools.client.model.ScheduleGameTeams;
import org.openapitools.client.model.ScheduleGameTicketsInner;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ScheduleGame
 */
public class ScheduleGameTest {
    private final ScheduleGame model = new ScheduleGame();

    /**
     * Model tests for ScheduleGame
     */
    @Test
    public void testScheduleGame() {
        // TODO: test ScheduleGame
    }

    /**
     * Test the property 'gamePk'
     */
    @Test
    public void gamePkTest() {
        // TODO: test gamePk
    }

    /**
     * Test the property 'link'
     */
    @Test
    public void linkTest() {
        // TODO: test link
    }

    /**
     * Test the property 'gameType'
     */
    @Test
    public void gameTypeTest() {
        // TODO: test gameType
    }

    /**
     * Test the property 'season'
     */
    @Test
    public void seasonTest() {
        // TODO: test season
    }

    /**
     * Test the property 'gameDate'
     */
    @Test
    public void gameDateTest() {
        // TODO: test gameDate
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'teams'
     */
    @Test
    public void teamsTest() {
        // TODO: test teams
    }

    /**
     * Test the property 'linescore'
     */
    @Test
    public void linescoreTest() {
        // TODO: test linescore
    }

    /**
     * Test the property 'venue'
     */
    @Test
    public void venueTest() {
        // TODO: test venue
    }

    /**
     * Test the property 'tickets'
     */
    @Test
    public void ticketsTest() {
        // TODO: test tickets
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

}
