/*
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import java.math.BigDecimal;
import org.openapitools.client.model.Conferences;
import org.openapitools.client.model.Division;
import org.openapitools.client.model.Error;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for ConferencesApi
 */
@Ignore
public class ConferencesApiTest {

    private final ConferencesApi api = new ConferencesApi();

    
    /**
     * Get an NHL conference.
     *
     * You can use this to also retrieve inactive conferences. For example, the ID for the World Cup of Hockey is &#x60;7&#x60;.
     */
    @Test
    public void getConferenceTest()  {
        BigDecimal id = null;
        Division response = api.getConference(id).block();

        // TODO: test validations
    }
    
    /**
     * Get all current NHL conferences.
     *
     * This only retrieves active conferences. For inactive conferences, use &#x60;/conferences/{id}&#x60;.
     */
    @Test
    public void getConferencesTest()  {
        Conferences response = api.getConferences().block();

        // TODO: test validations
    }
    
}
