/*
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import java.math.BigDecimal;
import org.openapitools.client.model.Draft;
import org.openapitools.client.model.DraftProspects;
import org.openapitools.client.model.Error;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for DraftApi
 */
@Ignore
public class DraftApiTest {

    private final DraftApi api = new DraftApi();

    
    /**
     * Get round-by-round data for current year&#39;s NHL Entry Draft.
     *
     * 
     */
    @Test
    public void getDraftTest()  {
        Draft response = api.getDraft().block();

        // TODO: test validations
    }
    
    /**
     * Get round-by-round data for a specific year&#39;s NHL Entry Draft.
     *
     * 
     */
    @Test
    public void getDraftByYearTest()  {
        BigDecimal year = null;
        Draft response = api.getDraftByYear(year).block();

        // TODO: test validations
    }
    
    /**
     * Get an NHL Entry Draft prospect.
     *
     * 
     */
    @Test
    public void getDraftProspectTest()  {
        BigDecimal id = null;
        DraftProspects response = api.getDraftProspect(id).block();

        // TODO: test validations
    }
    
    /**
     * Get all NHL Entry Draft prospects.
     *
     * Be forewarned that this endpoint returns a **lot** of data and there does not appear to be a way to paginate results.
     */
    @Test
    public void getDraftProspectsTest()  {
        DraftProspects response = api.getDraftProspects().block();

        // TODO: test validations
    }
    
}
