/*
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import java.math.BigDecimal;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.PlayerStats;
import org.openapitools.client.model.Players;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for PlayersApi
 */
@Ignore
public class PlayersApiTest {

    private final PlayersApi api = new PlayersApi();

    
    /**
     * Get an NHL player.
     *
     * 
     */
    @Test
    public void getPlayerTest()  {
        BigDecimal id = null;
        Players response = api.getPlayer(id).block();

        // TODO: test validations
    }
    
    /**
     * Get specific statistics for an NHL player.
     *
     * 
     */
    @Test
    public void getPlayerStatsTest()  {
        BigDecimal id = null;
        String stats = null;
        BigDecimal season = null;
        PlayerStats response = api.getPlayerStats(id, stats, season).block();

        // TODO: test validations
    }
    
}
