/*
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.Error;
import java.time.LocalDate;
import org.openapitools.client.model.Schedule;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for ScheduleApi
 */
@Ignore
public class ScheduleApiTest {

    private final ScheduleApi api = new ScheduleApi();

    
    /**
     * Get the NHL game schedule.
     *
     * 
     */
    @Test
    public void getScheduleTest()  {
        String expand = null;
        String teamId = null;
        LocalDate startDate = null;
        LocalDate endDate = null;
        Schedule response = api.getSchedule(expand, teamId, startDate, endDate).block();

        // TODO: test validations
    }
    
}
