/*
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.Error;
import java.time.LocalDate;
import org.openapitools.client.model.StandingTypesInner;
import org.openapitools.client.model.Standings;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for StandingsApi
 */
@Ignore
public class StandingsApiTest {

    private final StandingsApi api = new StandingsApi();

    
    /**
     * Get all available NHL standing types.
     *
     * 
     */
    @Test
    public void getStandingTypesTest()  {
        List<StandingTypesInner> response = api.getStandingTypes().collectList().block();

        // TODO: test validations
    }
    
    /**
     * Get NHL division standings.
     *
     * 
     */
    @Test
    public void getStandingsTest()  {
        LocalDate season = null;
        LocalDate date = null;
        Standings response = api.getStandings(season, date).block();

        // TODO: test validations
    }
    
    /**
     * Get NHL standings for a specific standing type.
     *
     * 
     */
    @Test
    public void getStandingsByTypeTest()  {
        String type = null;
        Standings response = api.getStandingsByType(type).block();

        // TODO: test validations
    }
    
}
