/*
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.Error;
import org.openapitools.client.model.StatTypesInner;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for StatsApi
 */
@Ignore
public class StatsApiTest {

    private final StatsApi api = new StatsApi();

    
    /**
     * Get all available NHL statistic types.
     *
     * 
     */
    @Test
    public void getStatTypesTest()  {
        List<StatTypesInner> response = api.getStatTypes().collectList().block();

        // TODO: test validations
    }
    
}
