/*
 * NHL API
 * Documenting the publicly accessible portions of the NHL API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import java.math.BigDecimal;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.Rosters;
import org.openapitools.client.model.Team;
import org.openapitools.client.model.TeamStats;
import org.openapitools.client.model.Teams;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for TeamsApi
 */
@Ignore
public class TeamsApiTest {

    private final TeamsApi api = new TeamsApi();

    
    /**
     * Get an NHL team.
     *
     * 
     */
    @Test
    public void getTeamTest()  {
        BigDecimal id = null;
        String expand = null;
        BigDecimal season = null;
        Team response = api.getTeam(id, expand, season).block();

        // TODO: test validations
    }
    
    /**
     * Get an NHL team&#39;s roster.
     *
     * 
     */
    @Test
    public void getTeamRosterTest()  {
        BigDecimal id = null;
        BigDecimal season = null;
        Rosters response = api.getTeamRoster(id, season).block();

        // TODO: test validations
    }
    
    /**
     * Get all statistics for an NHL team.
     *
     * 
     */
    @Test
    public void getTeamStatsTest()  {
        BigDecimal id = null;
        TeamStats response = api.getTeamStats(id).block();

        // TODO: test validations
    }
    
    /**
     * Get all NHL teams.
     *
     * 
     */
    @Test
    public void getTeamsTest()  {
        String expand = null;
        BigDecimal season = null;
        Teams response = api.getTeams(expand, season).block();

        // TODO: test validations
    }
    
}
